name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run comprehensive tests
      run: npm run test:comprehensive
    
    - name: Run quick tests
      run: npm run test:quick
    
    - name: Test the tool on itself
      run: node bin/auto-readme-lite.js --dry-run
    
    - name: Test with specific sections
      run: node bin/auto-readme-lite.js --sections api,cli,scripts --dry-run 