name: Update README

on:
  push:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'bin/**'
      - 'package.json'
      - '!README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update README
      run: node bin/auto-readme-lite.js --sections api,cli,scripts
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: auto-update README sections"
        git push 